### ISSUE TITLE
Remove Google apps non essential records

### ISSUE THREAD

**Issue by weppos** [aetrion/dnsimple-services#27]
It looks like Google apps has changed a bit since we added the service configuration.

Specifically:

- docs is no longer supported

    ![screen shot 2015-09-03 at 21 30 34](https://cloud.githubusercontent.com/assets/5387/9669021/1c86786c-5285-11e5-88f9-ac1085a21dd9.png)

- sites is no longer supported, unless you enable the feature

    ![screen shot 2015-09-03 at 21 30 41](https://cloud.githubusercontent.com/assets/5387/9669029/23f74f22-5285-11e5-99c5-69001290fd10.png)

- [jabber is not even mentioned anymore](https://support.google.com/a/answer/112038?hl=en).

I suggest to remove jabber, docs and sites. Any objection @aetrion/dnsimple ?

**Comment by martinisoft** [comment]
None from me @weppos 

Drive is the new docs by the by.
