### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by sbastn** [aetrion/dnsimple-services#49]
Services can now be categorized. I am proposing the following categories to be documented and applied to existing services:

* Blogging (tumblr, ...)
* Email (mailgun, ...)
* Hosting (shopify, ...)
* Infrastructure (cloudflare, ....)
* Marketing (kickoff labs, ...)
* Support (tenderapp, ...)

Anything you'd like to add/remove?

**Comment by weppos** [comment]
They seems accurate. Do they include all the services we have listed so far?

I'm not 100% convinced by Infrastructure vs Hosting. They seems to overlap quite a bit.

**Comment by sbastn** [comment]
Maybe eCommerce is a better name for Hosting? We have shopify, squarespace and supadupa that fit that description.

For infrastructure, I had in mind services like CDN and cloud providers like Amazon S3, Beanstalk, Azure, Fastly, etc..

But we can start with only 1 category and then decide if we want to split them apart.

**Comment by sbastn** [comment]
Closed by #51
